app:
  name: rss-agent

feishu:
  producthunt-daily:
    webhook_url: https://open.feishu.cn/open-apis/bot/v2/hook/your-webhook-url
    cron: "0 16 * * *" # 每天16点0分0秒执行
    length: 6

fetcher:
  interval: 30
  product_hunt:
    enabled: true
  rss:
    - name: best blogs
      url: https://www.bestblogs.dev/en/feeds/rss?category=ai&minScore=90
      enabled: true
